### GET request to example server
GET {{server}}/home

###

GET {{server}}/controlEndpoint

###

POST {{server}}/myEndpoint

###

GET {{server}}/home

###

GET {{server}}/api/item/42
Accept: application/json

###

POST {{server}}/api/myEndpoint
Accept: application/json

{
  "name": "John Doe",
  "age": 30
}
###